version: "3.9"
services:
  job_seeking_minio:
    container_name: job_seeking_minio
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root@1234
      - MINIO_DEFAULT_BUCKETS=default_buckets
    restart: always
    command: server --console-address :9001 /data
    networks:
      - job-seeking

  job_seeking_mysql_db:
    container_name: job_seeking_mysql_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_seeking
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "33069:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - job-seeking

  job-seeking-app:
    depends_on:
      - job_seeking_minio
      - job_seeking_mysql_db
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: job-seeking-app
    ports:
      - '8088:8088'
    networks:
      - job-seeking

volumes:
  minio_data:
  db_data:

networks:
  job-seeking:
    driver: bridge

